name: Manual Workflow with Concurrency Group

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  print-group-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Concurrency Group Name
      run: echo "El nombre del grupo de concurrencia es: ci-${{ github.ref }}"

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: false